In [0]:
# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)



In [2]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [3]:
from keras.models import Sequential
from keras.layers import Conv1D,Dense,Flatten,MaxPooling1D

Using TensorFlow backend.


In [0]:
n_features=1

In [0]:
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1,activation='linear'))

In [0]:
#compile the model
model.compile(optimizer='adam', loss='mse')

In [0]:
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [7]:
# fit model
model.fit(X, y, epochs=1000, verbose=0)

In [0]:
from numpy import array    

In [0]:
xt=array([70, 80, 90])
xt=xt.reshape((1,n_steps,n_features))

In [0]:
yt=model.predict(xt,verbose=0)

In [21]:
print(yt)

[[101.80365]]
