In [0]:
import numpy as np
from numpy import array

In [0]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

In [4]:
print(in_seq1)
print(in_seq2)
print(out_seq)

[10 20 30 40 50 60 70 80 90]
[15 25 35 45 55 65 75 85 95]
[ 25  45  65  85 105 125 145 165 185]


In [0]:
#reshape data
in_seq1=in_seq1.reshape((len(in_seq1),1))
in_seq2=in_seq2.reshape((len(in_seq2),1))
out_seq=out_seq.reshape((len(out_seq),1))

In [0]:
#merge the seqs
data=np.hstack((in_seq1,in_seq2,out_seq))

In [9]:
#Dataset
print(data)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [0]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [11]:
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(data, n_steps)
print(X.shape, y.shape)

(7, 3, 2) (7,)


In [12]:
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [13]:
# print(X)

[[[10 15]
  [20 25]
  [30 35]]

 [[20 25]
  [30 35]
  [40 45]]

 [[30 35]
  [40 45]
  [50 55]]

 [[40 45]
  [50 55]
  [60 65]]

 [[50 55]
  [60 65]
  [70 75]]

 [[60 65]
  [70 75]
  [80 85]]

 [[70 75]
  [80 85]
  [90 95]]]


In [0]:
from keras.models import Sequential
from keras.layers import Conv1D,Dense,Dropout,Flatten,MaxPooling1D

In [0]:
n_features=2

In [0]:
#define the model

model=Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1,activation='linear'))

In [0]:
#compile

model.compile(optimizer='adam',loss='mse')

In [30]:
#train
model.fit(X,y,epochs=1000,verbose=1)

Epoch 1/1000
7/7 [==============================] - 6s 874ms/step - loss: 10075.7109
Epoch 2/1000
7/7 [==============================] - 0s 618us/step - loss: 9469.2119
Epoch 3/1000
7/7 [==============================] - 0s 909us/step - loss: 8878.1670
Epoch 4/1000
7/7 [==============================] - 0s 657us/step - loss: 8298.8838
Epoch 5/1000
7/7 [==============================] - 0s 610us/step - loss: 7740.7446
Epoch 6/1000
7/7 [==============================] - 0s 602us/step - loss: 7206.8286
Epoch 7/1000
7/7 [==============================] - 0s 635us/step - loss: 6690.0942
Epoch 8/1000
7/7 [==============================] - 0s 651us/step - loss: 6185.2065
Epoch 9/1000
7/7 [==============================] - 0s 558us/step - loss: 5689.5542
Epoch 10/1000
7/7 [==============================] - 0s 448us/step - loss: 5203.0796
Epoch 11/1000
7/7 [==============================] - 0s 385us/step - loss: 4728.8994
Epoch 12/1000
7/7 [==============================] - 0s 746us/step - loss

In [34]:
#preparing prediction input

xt=np.array([[80, 85], [90, 95], [100, 105]])
xt=xt.reshape((1,n_steps,n_features))
xt.shape

(1, 3, 2)

In [0]:
#prediction

yt=model.predict(xt,verbose=0)

In [36]:
print(yt)

[[206.36623]]
